const express = require('express');
const router = express.Router();
const prisma = require('../prismaClient');
const { requireRole } = require('../middleware/authMiddleware');

// Anyone logged in can rate/flag
router.use(requireRole(['EMPLOYEE', 'TECHNICIAN', 'ADMIN']));

// Submit a Location Rating
router.post('/rate', async (req, res) => {
  const { location, rating } = req.body;
  if (!location || !rating) return res.status(400).json({ success: false, message: 'Missing fields' });

  try {
    const feedback = await prisma.locationFeedback.create({
      data: { location, rating: parseInt(rating) }
    });
    res.json({ success: true, feedback });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Server error' });
  }
});

// Submit an Anonymous Flag
router.post('/flag', async (req, res) => {
  const { location, category } = req.body;
  if (!location || !category) return res.status(400).json({ success: false, message: 'Missing fields' });

  try {
    const flag = await prisma.anonymousFlag.create({
      data: { location, category }
    });

    // Check if there are 3 flags for this location + category within last 24h
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const recentFlagsCount = await prisma.anonymousFlag.count({
      where: {
        location,
        category,
        createdAt: { gte: twentyFourHoursAgo }
      }
    });

    if (recentFlagsCount >= 3) {
      // Check if there's already an active ticket for this
      const activeTicket = await prisma.maintenanceRequest.findFirst({
        where: {
          location,
          category,
          status: { in: ['PENDING', 'IN_PROGRESS', 'ESCALATED'] }
        }
      });

      if (!activeTicket) {
        // Auto-create a ticket
        const newTicket = await prisma.maintenanceRequest.create({
          data: {
            title: `[AUTO] Unreported ${category} Issue in ${location}`,
            description: `This ticket was automatically generated because 3 or more anonymous flags were submitted for ${location} (${category}) within 24 hours.`,
            category,
            priority: 'MEDIUM',
            location,
            isAutoGenerated: true,
            status: 'PENDING'
          }
        });
        if (req.io) req.io.emit('ticket_created', newTicket);
      }
    }

    res.json({ success: true, flag });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Server error' });
  }
});

module.exports = router;
